language: php

branches:
    only:
        - master

php:
    - 5.6
    - hhvm
before_script:
    - composer install --dev --prefer-source --no-interaction
    - php artisan migrate --seed

script: phpunit tests
